[2020-07-28 14:14:10 -0400] [44231] [CRITICAL] WORKER TIMEOUT (pid:44234)
[2020-07-28 14:14:10 -0400] [44231] [CRITICAL] WORKER TIMEOUT (pid:44235)
[2020-07-28 14:14:10 -0400] [44231] [CRITICAL] WORKER TIMEOUT (pid:44236)
[2020-07-28 14:14:10 -0400] [44231] [CRITICAL] WORKER TIMEOUT (pid:44237)
[2020-07-28 14:14:10 -0400] [44231] [CRITICAL] WORKER TIMEOUT (pid:44238)
[2020-07-28 14:14:10 -0400] [44231] [CRITICAL] WORKER TIMEOUT (pid:44239)
[2020-07-28 14:14:10 -0400] [44231] [CRITICAL] WORKER TIMEOUT (pid:44240)
[2020-07-28 14:14:10 -0400] [44231] [CRITICAL] WORKER TIMEOUT (pid:44241)
[2020-07-28 14:14:10 -0400] [44231] [CRITICAL] WORKER TIMEOUT (pid:44242)
[2020-07-28 14:18:58 -0400] [44231] [CRITICAL] WORKER TIMEOUT (pid:49105)
[2020-07-28 14:26:08 -0400] [44231] [CRITICAL] WORKER TIMEOUT (pid:49106)
[2020-07-28 14:26:08 -0400] [44231] [CRITICAL] WORKER TIMEOUT (pid:49107)
[2020-07-28 14:26:08 -0400] [44231] [CRITICAL] WORKER TIMEOUT (pid:49108)
[2020-07-28 14:26:08 -0400] [44231] [CRITICAL] WORKER TIMEOUT (pid:49109)
[2020-07-28 14:26:08 -0400] [44231] [CRITICAL] WORKER TIMEOUT (pid:49110)
[2020-07-28 14:26:08 -0400] [44231] [CRITICAL] WORKER TIMEOUT (pid:49111)
[2020-07-28 14:26:08 -0400] [44231] [CRITICAL] WORKER TIMEOUT (pid:49112)
[2020-07-28 14:26:08 -0400] [44231] [CRITICAL] WORKER TIMEOUT (pid:49113)
[2020-07-28 14:26:08 -0400] [44231] [CRITICAL] WORKER TIMEOUT (pid:49173)
[2020-07-28 15:18:16 -0400] [51633] [CRITICAL] WORKER TIMEOUT (pid:51636)
[2020-07-28 15:18:16 -0400] [51633] [CRITICAL] WORKER TIMEOUT (pid:51637)
[2020-07-28 15:18:16 -0400] [51633] [CRITICAL] WORKER TIMEOUT (pid:51638)
[2020-07-28 15:18:16 -0400] [51633] [CRITICAL] WORKER TIMEOUT (pid:51639)
[2020-07-28 15:18:16 -0400] [51633] [CRITICAL] WORKER TIMEOUT (pid:51640)
[2020-07-28 15:18:16 -0400] [51633] [CRITICAL] WORKER TIMEOUT (pid:51641)
[2020-07-28 15:18:16 -0400] [51633] [CRITICAL] WORKER TIMEOUT (pid:51642)
[2020-07-28 15:18:16 -0400] [51633] [CRITICAL] WORKER TIMEOUT (pid:51643)
[2020-07-28 15:18:16 -0400] [51633] [CRITICAL] WORKER TIMEOUT (pid:51644)
[2020-07-28 15:40:50 -0400] [51633] [CRITICAL] WORKER TIMEOUT (pid:53116)
[2020-07-28 15:40:50 -0400] [51633] [CRITICAL] WORKER TIMEOUT (pid:53117)
[2020-07-28 15:40:50 -0400] [51633] [CRITICAL] WORKER TIMEOUT (pid:53118)
[2020-07-28 15:40:50 -0400] [51633] [CRITICAL] WORKER TIMEOUT (pid:53119)
[2020-07-28 15:40:50 -0400] [51633] [CRITICAL] WORKER TIMEOUT (pid:53120)
[2020-07-28 15:40:50 -0400] [51633] [CRITICAL] WORKER TIMEOUT (pid:53122)
[2020-07-28 15:40:50 -0400] [51633] [CRITICAL] WORKER TIMEOUT (pid:53124)
[2020-07-28 15:40:50 -0400] [51633] [CRITICAL] WORKER TIMEOUT (pid:53125)
[2020-07-28 15:40:50 -0400] [51633] [CRITICAL] WORKER TIMEOUT (pid:53126)
[2020-07-28 15:56:49 -0400] [51633] [CRITICAL] WORKER TIMEOUT (pid:53184)
[2020-07-28 15:56:49 -0400] [51633] [CRITICAL] WORKER TIMEOUT (pid:53185)
[2020-07-28 15:56:49 -0400] [51633] [CRITICAL] WORKER TIMEOUT (pid:53186)
[2020-07-28 15:56:49 -0400] [51633] [CRITICAL] WORKER TIMEOUT (pid:53187)
[2020-07-28 15:56:49 -0400] [51633] [CRITICAL] WORKER TIMEOUT (pid:53188)
[2020-07-28 15:56:49 -0400] [51633] [CRITICAL] WORKER TIMEOUT (pid:53189)
[2020-07-28 15:56:49 -0400] [51633] [CRITICAL] WORKER TIMEOUT (pid:53190)
[2020-07-28 15:56:49 -0400] [51633] [CRITICAL] WORKER TIMEOUT (pid:53191)
[2020-07-28 15:56:49 -0400] [51633] [CRITICAL] WORKER TIMEOUT (pid:53192)
[2020-07-29 00:30:57 -0400] [59223] [CRITICAL] WORKER TIMEOUT (pid:59226)
[2020-07-29 00:30:57 -0400] [59223] [CRITICAL] WORKER TIMEOUT (pid:59227)
[2020-07-29 00:30:57 -0400] [59223] [CRITICAL] WORKER TIMEOUT (pid:59228)
[2020-07-29 00:30:57 -0400] [59223] [CRITICAL] WORKER TIMEOUT (pid:59229)
[2020-07-29 00:30:57 -0400] [59223] [CRITICAL] WORKER TIMEOUT (pid:59230)
[2020-07-29 00:30:57 -0400] [59223] [CRITICAL] WORKER TIMEOUT (pid:59231)
[2020-07-29 00:30:57 -0400] [59223] [CRITICAL] WORKER TIMEOUT (pid:59232)
[2020-07-29 00:30:57 -0400] [59223] [CRITICAL] WORKER TIMEOUT (pid:59233)
[2020-07-29 00:30:57 -0400] [59223] [CRITICAL] WORKER TIMEOUT (pid:59234)
[2020-07-29 09:27:56 -0400] [59223] [CRITICAL] WORKER TIMEOUT (pid:87774)
[2020-07-29 09:27:56 -0400] [59223] [CRITICAL] WORKER TIMEOUT (pid:87775)
[2020-07-29 09:27:56 -0400] [59223] [CRITICAL] WORKER TIMEOUT (pid:87776)
[2020-07-29 09:27:56 -0400] [59223] [CRITICAL] WORKER TIMEOUT (pid:87777)
[2020-07-29 09:27:56 -0400] [59223] [CRITICAL] WORKER TIMEOUT (pid:87778)
[2020-07-29 09:27:56 -0400] [59223] [CRITICAL] WORKER TIMEOUT (pid:87779)
[2020-07-29 09:27:56 -0400] [59223] [CRITICAL] WORKER TIMEOUT (pid:87780)
[2020-07-29 09:27:56 -0400] [59223] [CRITICAL] WORKER TIMEOUT (pid:87781)
[2020-07-29 09:27:56 -0400] [59223] [CRITICAL] WORKER TIMEOUT (pid:87782)
[2020-07-29 21:54:49 -0400] [65108] [CRITICAL] WORKER TIMEOUT (pid:65111)
[2020-07-29 21:54:49 -0400] [65108] [CRITICAL] WORKER TIMEOUT (pid:65112)
[2020-07-29 21:54:49 -0400] [65108] [CRITICAL] WORKER TIMEOUT (pid:65113)
[2020-07-29 21:54:49 -0400] [65108] [CRITICAL] WORKER TIMEOUT (pid:65114)
[2020-07-29 21:54:49 -0400] [65108] [CRITICAL] WORKER TIMEOUT (pid:65115)
[2020-07-29 21:54:49 -0400] [65108] [CRITICAL] WORKER TIMEOUT (pid:65116)
[2020-07-29 21:54:49 -0400] [65108] [CRITICAL] WORKER TIMEOUT (pid:65117)
[2020-07-29 21:54:49 -0400] [65108] [CRITICAL] WORKER TIMEOUT (pid:65118)
[2020-07-29 21:54:49 -0400] [65108] [CRITICAL] WORKER TIMEOUT (pid:65119)
[2020-07-30 09:24:58 -0400] [65108] [CRITICAL] WORKER TIMEOUT (pid:80061)
[2020-07-30 09:24:58 -0400] [65108] [CRITICAL] WORKER TIMEOUT (pid:80063)
[2020-07-30 09:24:58 -0400] [65108] [CRITICAL] WORKER TIMEOUT (pid:80064)
[2020-07-30 09:24:58 -0400] [65108] [CRITICAL] WORKER TIMEOUT (pid:80065)
[2020-07-30 09:24:58 -0400] [65108] [CRITICAL] WORKER TIMEOUT (pid:80066)
[2020-07-30 09:24:58 -0400] [65108] [CRITICAL] WORKER TIMEOUT (pid:80067)
[2020-07-30 09:24:58 -0400] [65108] [CRITICAL] WORKER TIMEOUT (pid:80068)
[2020-07-30 09:24:58 -0400] [65108] [CRITICAL] WORKER TIMEOUT (pid:80069)
[2020-07-30 11:18:21 -0400] [65108] [CRITICAL] WORKER TIMEOUT (pid:80062)
[2020-07-30 11:18:22 -0400] [65108] [CRITICAL] WORKER TIMEOUT (pid:29831)
[2020-07-30 11:18:22 -0400] [65108] [CRITICAL] WORKER TIMEOUT (pid:29832)
[2020-07-30 11:18:22 -0400] [65108] [CRITICAL] WORKER TIMEOUT (pid:29833)
[2020-07-30 11:18:22 -0400] [65108] [CRITICAL] WORKER TIMEOUT (pid:29834)
[2020-07-30 11:18:22 -0400] [65108] [CRITICAL] WORKER TIMEOUT (pid:29838)
2020-08-11 15:26:33,029 browser_type_not_allowed (1014) {'assignmentId': 'debugA4MPZV', 'hitId': 'debug72D03J', 'workerId': 'debugLHMM9T', 'mode': 'debug'}
2020-08-11 15:26:33,121 Exception on /apple-touch-icon-precomposed.png [GET]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 747, in regularpage
    return render_template(pagename)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 117, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: apple-touch-icon-precomposed.png
2020-08-11 15:26:33,171 Exception on /apple-touch-icon.png [GET]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 747, in regularpage
    return render_template(pagename)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 117, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: apple-touch-icon.png
2020-08-11 15:27:41,823 browser_type_not_allowed (1014) {'assignmentId': 'debugTZCPU0', 'hitId': 'debug4L4WOV', 'workerId': 'debugQPN0F4', 'mode': 'debug'}
2020-08-11 15:27:41,874 Exception on /apple-touch-icon-precomposed.png [GET]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 747, in regularpage
    return render_template(pagename)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 117, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: apple-touch-icon-precomposed.png
2020-08-11 15:27:41,890 Exception on /apple-touch-icon.png [GET]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 747, in regularpage
    return render_template(pagename)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 117, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: apple-touch-icon.png
[2020-08-17 18:07:48 -0400] [15297] [CRITICAL] WORKER TIMEOUT (pid:15300)
[2020-08-17 18:07:48 -0400] [15297] [CRITICAL] WORKER TIMEOUT (pid:15301)
[2020-08-17 18:07:48 -0400] [15297] [CRITICAL] WORKER TIMEOUT (pid:15302)
[2020-08-17 18:07:48 -0400] [15297] [CRITICAL] WORKER TIMEOUT (pid:15303)
[2020-08-17 18:07:48 -0400] [15297] [CRITICAL] WORKER TIMEOUT (pid:15304)
[2020-08-17 18:07:48 -0400] [15297] [CRITICAL] WORKER TIMEOUT (pid:15305)
[2020-08-17 18:07:48 -0400] [15297] [CRITICAL] WORKER TIMEOUT (pid:15306)
[2020-08-17 18:07:48 -0400] [15297] [CRITICAL] WORKER TIMEOUT (pid:15307)
[2020-08-17 18:07:48 -0400] [15297] [CRITICAL] WORKER TIMEOUT (pid:15308)
[2020-08-17 18:53:16 -0400] [15297] [CRITICAL] WORKER TIMEOUT (pid:39160)
[2020-08-17 18:53:16 -0400] [15297] [CRITICAL] WORKER TIMEOUT (pid:39161)
[2020-08-17 18:53:16 -0400] [15297] [CRITICAL] WORKER TIMEOUT (pid:39162)
[2020-08-17 18:53:16 -0400] [15297] [CRITICAL] WORKER TIMEOUT (pid:39163)
[2020-08-17 18:53:16 -0400] [15297] [CRITICAL] WORKER TIMEOUT (pid:39164)
[2020-08-17 18:53:16 -0400] [15297] [CRITICAL] WORKER TIMEOUT (pid:39165)
[2020-08-17 18:53:16 -0400] [15297] [CRITICAL] WORKER TIMEOUT (pid:39166)
[2020-08-17 18:53:16 -0400] [15297] [CRITICAL] WORKER TIMEOUT (pid:39167)
[2020-08-17 18:53:16 -0400] [15297] [CRITICAL] WORKER TIMEOUT (pid:39168)
[2020-08-18 12:51:36 -0400] [20560] [CRITICAL] WORKER TIMEOUT (pid:20563)
[2020-08-18 12:51:36 -0400] [20560] [CRITICAL] WORKER TIMEOUT (pid:20564)
[2020-08-18 12:51:36 -0400] [20560] [CRITICAL] WORKER TIMEOUT (pid:20569)
[2020-08-18 12:51:36 -0400] [20560] [CRITICAL] WORKER TIMEOUT (pid:20570)
[2020-08-18 12:51:36 -0400] [20560] [CRITICAL] WORKER TIMEOUT (pid:20571)
[2020-08-18 13:37:33 -0400] [20560] [CRITICAL] WORKER TIMEOUT (pid:20565)
[2020-08-18 13:37:33 -0400] [20560] [CRITICAL] WORKER TIMEOUT (pid:20566)
[2020-08-18 13:37:33 -0400] [20560] [CRITICAL] WORKER TIMEOUT (pid:20567)
[2020-08-18 13:37:33 -0400] [20560] [CRITICAL] WORKER TIMEOUT (pid:20568)
[2020-08-18 13:37:33 -0400] [20560] [CRITICAL] WORKER TIMEOUT (pid:20947)
[2020-08-18 13:37:33 -0400] [20560] [CRITICAL] WORKER TIMEOUT (pid:20948)
[2020-08-18 13:37:33 -0400] [20560] [CRITICAL] WORKER TIMEOUT (pid:20949)
[2020-08-18 13:37:33 -0400] [20560] [CRITICAL] WORKER TIMEOUT (pid:20950)
2020-08-23 14:02:18,746 Exception on /.ogg [GET]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 747, in regularpage
    return render_template(pagename)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 117, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .ogg
2020-08-23 14:04:10,621 Exception on /.ogg [GET]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 747, in regularpage
    return render_template(pagename)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 117, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .ogg
2020-08-23 14:21:33,243 Exception on /.ogg [GET]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 747, in regularpage
    return render_template(pagename)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 117, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .ogg
2020-08-23 14:23:08,322 Exception on /.ogg [GET]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 747, in regularpage
    return render_template(pagename)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 117, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .ogg
2020-08-23 14:23:53,369 Exception on /.ogg [GET]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 747, in regularpage
    return render_template(pagename)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 117, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .ogg
2020-08-23 14:24:31,184 Exception on /.ogg [GET]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 747, in regularpage
    return render_template(pagename)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 117, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .ogg
2020-08-23 14:55:08,162 Exception on /create_tasklist.py [GET]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 747, in regularpage
    return render_template(pagename)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 117, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tasklist.py
2020-08-23 14:55:53,059 Exception on /create_tasklist.py [GET]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 747, in regularpage
    return render_template(pagename)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 117, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tasklist.py
2020-08-23 15:25:14,925 Exception on /create_tasklist.py [GET]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 747, in regularpage
    return render_template(pagename)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 117, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tasklist.py
2020-08-23 15:26:18,691 Exception on /create_tasklist.py [GET]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 747, in regularpage
    return render_template(pagename)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 117, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tasklist.py
2020-08-23 15:28:27,070 Exception on /create_tasklist.py [GET]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 747, in regularpage
    return render_template(pagename)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 117, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tasklist.py
2020-08-26 14:39:43,366 Exception on /create_tasklist [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1841, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1856, in finalize_request
    response = self.make_response(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1982, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-08-26 14:44:22,109 Exception on /create_tasklist [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1841, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1856, in finalize_request
    response = self.make_response(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1982, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-08-26 14:44:51,565 Exception on /create_tasklist [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1841, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1856, in finalize_request
    response = self.make_response(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1982, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-08-26 14:49:42,244 Exception on /create_tasklist [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1841, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1856, in finalize_request
    response = self.make_response(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1982, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-08-26 14:50:14,341 Exception on /create_tasklist [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1841, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1856, in finalize_request
    response = self.make_response(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1982, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-08-26 14:53:47,092 Exception on /create_tasklist [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1841, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1856, in finalize_request
    response = self.make_response(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1982, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-08-26 14:56:57,083 Exception on /create_tasklist [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1841, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1856, in finalize_request
    response = self.make_response(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1982, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-08-26 14:59:12,691 Exception on /create_tasklist [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1841, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1856, in finalize_request
    response = self.make_response(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1982, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-08-26 15:00:04,631 Exception on /create_tasklist [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1841, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1856, in finalize_request
    response = self.make_response(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1982, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-08-26 15:01:49,871 Exception on /create_tasklist [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1841, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1856, in finalize_request
    response = self.make_response(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1982, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-08-26 15:24:37,757 Exception on /create_tasklist [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1841, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1856, in finalize_request
    response = self.make_response(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1982, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-08-31 17:43:54,156 Exception on /create_tasklist [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1841, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1856, in finalize_request
    response = self.make_response(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1982, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-08-31 17:50:15,720 Exception on /create_tasklist [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1841, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1856, in finalize_request
    response = self.make_response(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1982, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-10-20 10:52:11,737 Exception on /create_tasklist [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1841, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1856, in finalize_request
    response = self.make_response(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1982, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-10-20 11:17:17,148 Exception on /create_tasklist [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1841, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1856, in finalize_request
    response = self.make_response(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1982, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-10-20 11:57:15,444 Exception on /create_tasklist [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1841, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1856, in finalize_request
    response = self.make_response(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1982, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-10-20 13:05:09,077 Exception on /create_tasklist [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1841, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1856, in finalize_request
    response = self.make_response(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1982, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-10-20 14:18:55,303 Exception on /create_tasklist [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1841, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1856, in finalize_request
    response = self.make_response(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1982, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-10-20 14:25:01,148 Exception on /create_tasklist [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1841, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1856, in finalize_request
    response = self.make_response(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1982, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-10-20 14:25:16,998 Exception on /create_tasklist [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1841, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1856, in finalize_request
    response = self.make_response(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1982, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-10-20 14:30:53,815 Exception on /create_tasklist [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1841, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1856, in finalize_request
    response = self.make_response(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1982, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-10-20 14:33:16,097 Exception on /create_tasklist [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1841, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1856, in finalize_request
    response = self.make_response(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1982, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-10-20 14:36:28,178 Exception on /create_tasklist [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1841, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1856, in finalize_request
    response = self.make_response(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1982, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-10-20 14:38:19,531 Exception on /create_tasklist [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1841, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1856, in finalize_request
    response = self.make_response(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1982, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-10-20 14:39:44,951 Exception on /create_tasklist [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1841, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1856, in finalize_request
    response = self.make_response(rv)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1982, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
